# Generated by Django 5.1.6 on 2025-10-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentenrollment_admission_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='admission_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('one_time', 'One-Time'), ('monthly', 'Monthly'), ('installment', 'Installment')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online')], max_length=20, null=True),
        ),
    ]
