# Generated by Django 5.1.6 on 2025-07-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, unique=True, verbose_name='Course Name')),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Course Fee (₹)')),
                ('course_duration', models.PositiveIntegerField(verbose_name='Course Duration')),
                ('duration_type', models.CharField(choices=[('weeks', 'Weeks'), ('months', 'Months')], default='months', max_length=6, verbose_name='Duration Type')),
            ],
        ),
    ]
