# Generated by Django 5.1.6 on 2025-07-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text="This fee will automatically be added to every new student's payment", max_digits=10, verbose_name='Admission Fee (₹)'),
        ),
    ]
